name: "BMW-GithubActions-Example"

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Run JFrog CLI Ping
        run: jf rt ping
        
      - name:
        run: mvn -version

      - name: Configure Maven repositories in JFrog CLI
        run: |
          jf mvnc --repo-resolve-releases srs-maven-remote \
                  --repo-resolve-snapshots srs-maven-remote \
                  --repo-deploy-releases alpha-mvn-blr-libs-release \
                  --repo-deploy-snapshots team2-mvn-libs-snapshot
                  
      - name: JFrog Curation Audit Command
        run: jf ca
        
    

      - name: Publish build
        run: jf rt bp BMW-Training-mvn-publish ${{ github.run_number }}
